# Generated by Django 4.0.3 on 2022-04-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_authorreview_authorlike_authordislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
