# Generated by Django 4.0.3 on 2022-04-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_is_authorized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="is_authorized",
            new_name="is_author",
        ),
    ]
