# Generated by Django 4.0.3 on 2022-04-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_is_authorized_profile_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
