# Generated by Django 4.0.3 on 2022-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
