# Generated by Django 4.0.3 on 2022-04-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_is_author_alter_profile_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
