# Generated by Django 4.0.3 on 2022-03-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoreuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
