# Generated by Django 4.0.3 on 2022-03-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bookstoreuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_author',
        ),
    ]
