# Generated by Django 4.0.3 on 2022-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_is_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
