services:
  database:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      database:
        condition: service_healthy

volumes:
  data:
