# Generated by Django 4.0.3 on 2022-04-05 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_like_dislike_bookcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookComment',
            new_name='BookReview',
        ),
    ]
