# Generated by Django 4.0.3 on 2022-04-30 14:28

import bookstore.books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Action and adventure', 'Action and adventure'), ('Art / architecture', 'Art / architecture'), ('Alternate history', 'Alternate history'), ('Autobiography', 'Autobiography'), ('Anthology', 'Anthology'), ('Biography', 'Biography'), ('Business / economics', 'Business / economics'), ("Children's", "Children's"), ('Crafts / hobbies', 'Crafts / hobbies'), ('Classic', 'Classic'), ('Cookbook', 'Cookbook'), ('Comic book', 'Comic book'), ('Diary', 'Diary'), ('Dictionary', 'Dictionary'), ('Crime', 'Crime'), ('Encyclopedia', 'Encyclopedia'), ('Drama', 'Drama'), ('Guide', 'Guide'), ('Fairytale', 'Fairytale'), ('Health / fitness', 'Health / fitness'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Graphic novel', 'Graphic novel'), ('Home and garden', 'Home and garden'), ('Historical fiction', 'Historical fiction'), ('Humor', 'Humor'), ('Horror', 'Horror'), ('Journal', 'Journal'), ('Mystery', 'Mystery'), ('Math', 'Math'), ('Paranormal romance', 'Paranormal romance'), ('Memoir', 'Memoir'), ('Picture book', 'Picture book'), ('Philosophy', 'Philosophy'), ('Poetry', 'Poetry'), ('Prayer', 'Prayer'), ('Political thriller', 'Political thriller'), ('Religion, spirituality, and new age', 'Religion, spirituality, and new age'), ('Romance', 'Romance'), ('Textbook', 'Textbook'), ('Satire', 'Satire'), ('True crime', 'True crime'), ('Science fiction', 'Science fiction'), ('Review', 'Review'), ('Short story', 'Short story'), ('Science', 'Science'), ('Suspense', 'Suspense'), ('Self help', 'Self help'), ('Thriller', 'Thriller'), ('Sports and leisure', 'Sports and leisure'), ('Western', 'Western'), ('Travel', 'Travel')], max_length=35, validators=[bookstore.books.validators.validate_genre]),
        ),
    ]
